baseURL = 'https://yuu.ooo/'
languageCode = 'en-us'
title = 'yuu'
theme = 'hugo-tania'

[params]
  # Emoji will show before the blog title on site navbar.
  # titleEmoji  = "😎"

  # Logo will show before the blog title on site navbar.
  # titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = false

  siteName = "yuu"
  siteDesc = "yuu"
  author = "yuu"

  [params.colorScheme]
    # Enable toggle colorScheme
    # Default to true
    toggle = true
    # Default colorScheme
    # Default to auto
    # default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = "reiuyuu@gmail.com"
    facebook = ""
    github = "https://github.com/reiuyuu"
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = "https://twitter.com/reiuyuu"
    twitch = ""
    whatsapp = ""
  
  # Comments settigns
  [params.comments]
    enabled = false
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Posts"
  url = "/posts/"
[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]